version: '3.8'

services:
  # Node.js API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whackamole-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=whackamole
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - NODE_ENV=production
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX_REQUESTS=60
    restart: unless-stopped
    # Add a healthcheck that integrates with Docker
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => res.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: whackamole-db
    ports:
      # Map to a different host port to avoid conflicts with local PostgreSQL
      - "5433:5432"
    environment:
      - POSTGRES_DB=whackamole
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    name: whackamole-data
